services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434" # 暴露 Ollama 服务的默认端口
    volumes:
      # 挂载本地模型目录到容器内
      - ~/.ollama/models:/root/.ollama/models
    environment:
      # 配置环境变量，如果需要修改可以在这里调整
      OLLAMA_SERVER: http://0.0.0.0:11434
    deploy:
      resources:
        limits:
          memory: 10g # 限制容器使用的内存为 8GB
